# Generated by Django 5.2.3 on 2025-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_images/'),
        ),
    ]
